### ISSUE TITLE
‘LncPipeReporter’ install error

### ISSUE THREAD

**Issue by kodayu** [bioinformatist/LncPipeReporter#5]
Warning message:
package ‘LncPipeReporter’ is not available (for R version 3.4.2)

LncPipeReporter does not support R version 3.4.2? I can't install it in centos.

**Comment by bioinformatist** [comment]
Sorry that I've been working hard for graduating from fucking Nankai University recent days.

I'll try install it on Manjaro Linux with latest MRO first.

Could you confirm that you used the command `devtools::install_github("bioinformatist/LncPipeReporter")` (according to my README documentation)  for installation? Since I never release this package (not received by the journel yet) to CRAN or Bioconductor, you can't install it by command like `install.packages()`. Please check it.

And are you one of my teammate at SYSUCC? If so, please provide your server's IP as well as an account for testing, so that I can login and try install the package.

**Comment by kodayu** [comment]
Sorry that I forgot to reply this message, I download this package from github, and install.packages. devtools requires https, and I cann't connect to https at my cluster.

**Comment by kodayu** [comment]
How about deal with this problem on weekend, I can wait for you.

**Comment by bioinformatist** [comment]
It seems you are an user from SYSUCC, so you are Chinese, right?
You can refer to this [post](https://icannotendure.space/zh/post/r%E5%8C%85%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98/#%E4%BD%BF%E7%94%A8-devtools-install-github-%E6%8A%A5%E9%94%99biocinstaller%E5%AE%89%E8%A3%85%E4%B8%8D%E4%B8%8A).

**Comment by kodayu** [comment]
Yes, I will try it again, and I will request your help if there still be some problem.

**Comment by likelet** [comment]
it is funny to see this conversation. :)
